{"ast":null,"code":"import { AxiosError } from \"axios\";\nexport var ErrorResponse = {\n  error: string\n};\nexport function catchAxiosError(err) {\n  // Something happened in setting up the request that triggered an Error\n  console.log(\"Error\", err.message);\n  var message = \"Something happened in setting up the request that triggered an Error\";\n\n  if (err.response) {\n    // The request was made and the server responded with a status code\n    // that falls out of the range of 2xx\n    console.log(err.response.data.message);\n    console.log(err.response.status); // console.log(err.response.headers);\n\n    message = err.response.data.message;\n  } else if (err.request) {\n    // The request was made but no response was received\n    // `err.request` is an instance of XMLHttpRequest in the browser and an instance of\n    // http.ClientRequest in node.js\n    console.log(err.request);\n    message = \"The request was made, but no response was received\";\n  }\n\n  return {\n    error: message\n  };\n}","map":{"version":3,"sources":["/Users/williamforte/Canvas/uncle-steven/services/error.js"],"names":["AxiosError","ErrorResponse","error","string","catchAxiosError","err","console","log","message","response","data","status","request"],"mappings":"AAAA,SAASA,UAAT,QAA2B,OAA3B;AAEA,OAAO,IAAMC,aAAa,GAAG;AAC3BC,EAAAA,KAAK,EAAEC;AADoB,CAAtB;AAIP,OAAO,SAASC,eAAT,CAAyBC,GAAzB,EAA8B;AACnC;AACAC,EAAAA,OAAO,CAACC,GAAR,CAAY,OAAZ,EAAqBF,GAAG,CAACG,OAAzB;AACA,MAAIA,OAAO,GAAG,sEAAd;;AAEA,MAAIH,GAAG,CAACI,QAAR,EAAkB;AAChB;AACA;AACAH,IAAAA,OAAO,CAACC,GAAR,CAAYF,GAAG,CAACI,QAAJ,CAAaC,IAAb,CAAkBF,OAA9B;AACAF,IAAAA,OAAO,CAACC,GAAR,CAAYF,GAAG,CAACI,QAAJ,CAAaE,MAAzB,EAJgB,CAKhB;;AACAH,IAAAA,OAAO,GAAGH,GAAG,CAACI,QAAJ,CAAaC,IAAb,CAAkBF,OAA5B;AACD,GAPD,MAOO,IAAIH,GAAG,CAACO,OAAR,EAAiB;AACtB;AACA;AACA;AACAN,IAAAA,OAAO,CAACC,GAAR,CAAYF,GAAG,CAACO,OAAhB;AACAJ,IAAAA,OAAO,GAAG,oDAAV;AACD;;AACD,SAAO;AAAEN,IAAAA,KAAK,EAAEM;AAAT,GAAP;AACD","sourcesContent":["import { AxiosError } from \"axios\";\n\nexport const ErrorResponse = {\n  error: string\n}\n\nexport function catchAxiosError(err) {\n  // Something happened in setting up the request that triggered an Error\n  console.log(\"Error\", err.message);\n  let message = \"Something happened in setting up the request that triggered an Error\";\n\n  if (err.response) {\n    // The request was made and the server responded with a status code\n    // that falls out of the range of 2xx\n    console.log(err.response.data.message);\n    console.log(err.response.status);\n    // console.log(err.response.headers);\n    message = err.response.data.message;\n  } else if (err.request) {\n    // The request was made but no response was received\n    // `err.request` is an instance of XMLHttpRequest in the browser and an instance of\n    // http.ClientRequest in node.js\n    console.log(err.request);\n    message = \"The request was made, but no response was received\";\n  }\n  return { error: message };\n}\n"]},"metadata":{},"sourceType":"module"}